//HTMLWebseite erstellen
void EncodeFormHTMLFromConfigValuesnew()
{
  HTMLPageWithConfigForm = "";
  HTMLPageWithConfigForm = writehtmllong();
}

String writehtmllong()
{
  String HTMLPage;
  HTMLPage += "<!DOCTYPE html>"
              "<html>"
              "<head>"
              "<link href=\"http://fonts.googleapis.com/css?family=Corben:bold\" rel=\"stylesheet\" type=\"text/css\">"
              "<link href=\"http://fonts.googleapis.com/css?family=Nobile\" rel=\"stylesheet\" type=\"text/css\">"
              "<title>Wordclock by Uniquelymade</title>"
              "<style>"
              "/* CSS RESET ---------------------------------------------- */"
              "        "
              "*, div, span, header {"
              "    margin: 0px;"
              "    padding: 0px;"
              "    border: 0px solid #ff00ff;"
              "}"
              "/* apply a natural box layout model to all elements */"
              "        "
              "*, *:before, *:after {"
              "    -moz-box-sizing: border-box;"
              "    -webkit-box-sizing: border-box;"
              "    box-sizing: border-box;"
              "}"
              "/* clearfix */"
              "        "
              ".clearfix:after {"
              "    content: \".\";"
              "    display: block;"
              "    clear: both;"
              "    visibility: hidden;"
              "    line-height: 0;"
              "    height: 0;"
              "}"
              ".clearfix {"
              "    display: inline-block;"
              "}"
              "html[xmlns] .clearfix {"
              "    display: block;"
              "}"
              "* html .clearfix {"
              "    height: 1%;"
              "}"
              "/* CSS RESET ---------------------------------------------- */"
              "        "
              "html {"
              "    font-size: 62.5%;"
              "// font-family: 'Corben', Georgia, Times, serif;"
              "    font-family: 'Georgia';"
              "}"
              "h1, h2, h3, h4, a {"
              "    text-shadow: 5px 5px 5px #ccc;"
              "}"
              "summary {"
              "    font-size: 1.5rem;"
              "}"
              "h1 {"
              "    font-size: 2.9rem;"
              "}"
              "h2 {"
              "    font-size: 2rem;"
              "}"
              "h3, th {"
              "    font-size: 1.5rem;"
              "}"
              "h4 {"
              "    font-size: 1.7rem;"
              "}"
              "h5 {"
              "    font-size: 1.2rem;"
              "}"
              "p, div {"
              "    font-family: 'Nobile', Helvetica, Arial, sans-serif,;"
              "    font-size: 1.5rem;"
              "// border: 1px solid red;"
              "}"
              ".reset {"
              "    max-width: 100px;"
              "}"
              "input[type=submit] {"
              "    padding: 5px 15px;"
              "    background: #ccc;"
              "    border: 0 none;"
              "    cursor: pointer;"
              "    -webkit-border-radius: 5px;"
              "    border-radius: 5px;"
              "}"
              ".container {"
              "    display: flex;"
              "    flex-direction: row;"
              "    align-content: center;"
              "    align-items: center;"
              "    justify-content: center;"
              "    max-width: 800px;"
              "}"
              ".tablecontainer {"
              "    display: flex;"
              "    flex-direction: column;"
              "    align-content: center;"
              "    align-items: center;"
              "    justify-content: space-around;"
              "    max-width: 800px;"
              "}"
              ".evencontainer {"
              "    display: flex;"
              "    flex-direction: row;"
              "    align-content: center;"
              "    align-items: center;"
              "    justify-content: space-evenly;"
              "    max-width: 800px;"
              "}"
              ".spacediv {"
              "    height: 5rem;"
              "    width: 10px;"
              "}"
              ".centerdiv {"
              "    display: flex;"
              "    flex-direction: row;"
              "    align-content: center;"
              "    align-items: center;"
              "    justify-content: space-evenly;"
              "    max-width: 800px;"
              "}"
              ".buttonstyle {"
              "  color: #333333;"
              "  text-decoration: none;"
              "  background: #ccc;"
              "  padding: 5px 15px;"
              "  -webkit-border-radius: 5px;"
              "   border-radius: 5px;"
              "}"
              "input[type=color] {"
              "    padding: 1px;"
              "    border: 2px solid #ccc;"
              "    -webkit-border-radius: 5px;"
              "    border-radius: 5px;"
              "}"
              "select {"
              "    padding: 5px;"
              "    border: 2px solid #ccc;"
              "    -webkit-border-radius: 5px;"
              "    border-radius: 5px;"
              "}"
              "input[type=time] {"
              "    padding: 5px;"
              "    border: 2px solid #ccc;"
              "    -webkit-border-radius: 5px;"
              "    border-radius: 5px;"
              "}"
              "input[type=password] {"
              "    padding: 5px;"
              "    border: 2px solid #ccc;"
              "    -webkit-border-radius: 5px;"
              "    border-radius: 5px;"
              "}"
              "input[type=text] {"
              "    padding: 5px;"
              "    border: 2px solid #ccc;"
              "    -webkit-border-radius: 5px;"
              "    border-radius: 5px;"
              "}"
              "input[type=color]:focus {"
              "    border-color: #333;"
              "}"
              "summary:focus {"
              "    outline: none;"
              "}"
              "table {"
              "    table-layout: auto;"
              "}"
              ".tooltip {"
              "    position: relative;"
              "}"
              ".tooltip span[role=tooltip] {"
              "    display: none;"
              "}"
              ".percentage {"
              "    width: 50px;"
              "    align-content: center;"
              "    align-items: center;"
              "}"
              ".tooltip:hover span[role=tooltip] {"
              "    display: block;"
              "    position: absolute;"
              "    bottom: 2em;"
              "    left: -6em;"
              "    width: 15em;"
              "    padding: 0.5em;"
              "    z-index: 100;"
              "    color: #000;"
              "    background-color: #ffebe6;"
              "    border: solid 1px #c32e04;"
              "    border-radius: 0.2em;"
              "}"
              ".slidecontainer {"
              "    width: 300px;"
              "}"
              ".slider {"
              "    -webkit-appearance: none;"
              "    width: 100%;"
              "    height: 15px;"
              "    background: #d3d3d3;"
              "    padding: 5px;"
              "    border: 2px solid #ccc;"
              "    -webkit-border-radius: 5px;"
              "    border-radius: 5px;"
              "    outline: none;"
              "    opacity: 0.7;"
              "    -webkit-transition: .2s;"
              "    transition: opacity .2s;"
              "}"
              ".slider:hover {"
              "    opacity: 1;"
              "}"
              " .slider::-webkit-slider-thumb {"
              " -webkit-appearance: none;"
              " appearance: none;"
              " width: 25px;"
              " height: 25px;"
              " background: #4CAF50;"
              " cursor: pointer;"
              "}"
              " .slider::-moz-range-thumb {"
              " width: 25px;"
              " height: 25px;"
              " background: #4CAF50;"
              " cursor: pointer;"
              "}"
              "table {"
              "    border-collapse: separate;"
              "    border-spacing: 20px 0;"
              "}"
              "td {"
              "    padding: 10px 0;"
              "}"
              ".spacer1 {"
              "    height: 5rem;"
              "    width: 100%;"
              "}"
              ".spacer2 {"
              "    height: 3rem;"
              "    width: 100%;"
              "}"
              ".spacer3 {"
              "    height: 1rem;"
              "    width: 100%;"
              "}"
              ".spacer4 {"
              "    height: 5rem;"
              "    width: 100%;"
              "}"
              ".spacer5 {"
              "    height: 10rem;"
              "    width: 100%;"
              "}"
              "</style>"
              "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
              "<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\">"
              "</head>"
              ""
              "<body>"
              "<center>"
              "<div class=\"spacer1\"></div>"
              "<h1>Wordclock</h1>"
              "<div class=\"spacer3\"></div>"
              "<h2>by <a href=\"https://uniquelymade.de/en/homepage-en/\" target=\"_blank\">Uniquelymade</a></h2>"
              "<div class=\"spacer4\"></div>"
              "<h2>Generelle Einstellungen</h2>"
              "<div class=\"spacer3\"></div>"
              "<form>"
              "  <div class=\"container\">"
              "    <div>Farbe</div>"
              "    <div class=\"spacediv\"> </div>"
              "    <div>"
              "      <input type=\"color\" id=\"color\" name=\"Farbe\" value=\"" + ConfigValue[0] + "\">"
              "    </div>"
              "  </div>"
              "  <div class=\"spacer3\"></div>"
              "  <div class=\"container\">"
              "    <div class=\"slidecontainer\">"
              "      <input type=\"range\" min=\"0\" max=\"100\" name=\"Helligkeittag\" value=\"" + ConfigValue[1] + "\" class=\"slider\" id=\"ledbrightness\">"
              "    </div>"
              "    <div class=\"spacediv\"> </div>"
              "    <div class=\"centerdiv\"> <span id=\"demo\" class=\"percentage\"></span>%</div>"
              "  </div>"
              "  <div class=\"spacer3\"></div>"
              "  <div class=\"container\">"
              "    <div>Zeitzone</div>"
              "    <div class=\"spacediv\"> </div>"
              "    <div>"
              "      <select name=\"Zeitzone\">";
  for (int i = -12; i < 12; i++)
  {
    HTMLPage += "<option value=\"" + String(i) + "\" ";
    if (i == ConfigValue[2].toInt())
    {
      HTMLPage += "selected";
      Serial.println("selected printed");
    }
    HTMLPage += ">UTC" + String(i) + "</option>";
  }
  HTMLPage += "</select>"
              "    </div>"
              "    <div class=\"spacediv\"> </div>"
              "    <div>Auto. Sommerzeit?</div>"
              "    <div class=\"spacediv\"> </div>"
              "    <div>"
              "      <input type=\"hidden\" name=\"nachtruhe\" value=\"0\">"
              "      <input type=\"checkbox\" name=\"nachtruhe\" value=\"Summertime\"";
  if (ConfigValue[3] == "1")
  {
    HTMLPage += "checked ";
  }


  HTMLPage += ">"
              "    </div > "
              "  </div > "
              "  <div class = \"spacer3\"></div>"
              "  <h2>Ruhemodus</h2>"
              "  <div class=\"spacer3\"></div>"
              "  <div class=\"container\">"
              "    <div>Aktivieren</div>"
              "    <div class=\"spacediv\"> </div>"
              "    <div>"
              "      <input type=\"hidden\" name=\"nachtruhe\" value=\"0\">"
              "      <input type=\"checkbox\" name=\"nachtruhe\" value=\"nighttime\"";
  if (ConfigValue[4] == "1")
  {
    HTMLPage += "checked ";
  }
  HTMLPage += ">";
  HTMLPage += "    </div>"
              "  </div > "
              "  <div class = \"spacer3\"></div>"
              "  <div class=\"container\">"
              "    <div>Von:</div>"
              "    <div class=\"spacediv\"> </div>"
              "    <div>"
              "      <input size=\"5\" type=\"time\" name=\"Ruheab\" value=\"" + ConfigValue[5] + "\" />"
              "    </div>"
              "    <div class=\"spacediv\"> </div>"
              "    <div>Bis:</div>"
              "    <div class=\"spacediv\"> </div>"
              "    <div>"
              "      <input size=\"5\" type=\"time\" name=\"Ruhebis\" value=\"" + ConfigValue[6] + "\" />"
              "    </div>"
              "  </div>"
              "  <div class=\"spacer3\"></div>"
              "  <div class=\"container\">"
              "    <div class=\"slidecontainer\">"
              "      <input type=\"range\" min=\"0\" max=\"100\" name=\"Helligkeitnachts\" value=\"" + ConfigValue[7] + "\" class=\"slider\" id=\"ledbrightnessnight\">"
              "    </div>"
              "    <div class=\"spacediv\"> </div>"
              "    <div class=\"centerdiv\"> <span id=\"lednight\" class=\"percentage\"></span>%</div>"
              "  </div>"
              "  <div class=\"spacer3\"></div>"
              "  <input type=\"submit\" value=\"Einstellungen Übernehmen\" />"
              "  <div class=\"spacer2\"></div>";

  if (WiFi.status() == WL_CONNECTED)
  {
    wificonnected = true;
  }

  if (wificonnected == true)
  {
    HTMLPage += "<div class=\"container\">"
                "      <div>Verbunden mit: </div>"
                "      <div class=\"spacediv\"> </div>"
                "      <div>" + ConfigValue[8] + "</div>"
                "      <div class=\"spacediv\"> </div>"
                "      <div>Mit IP: </div>"
                "      <div class=\"spacediv\"> </div>"
                "      <div>" + WiFi.localIP().toString() + "</div>"
                "    </div>";
  }

  if (wificonnected == false)
  {
    HTMLPage += "<div class=\"container\"> Mit keinem Netzwerk verbunden </div>";
  }
  HTMLPage += "  <details>"
              "    <summary>Netzwerkeinstellungen</summary>";




  HTMLPage += "    <div class=\"spacer3\"></div>"
              "    <div class=\"container\">"
              "      <div>Netzwerk </div>"
              "      <div class=\"spacediv\"> </div>"
              "      <div>"
              "        <input type=\"text\" name=\"SSID\" value=\"" + ConfigValue[8] + "\" />"
              "      </div>"
              "    </div>"
              "    <div class=\"container\">"
              "      <div>Password </div>"
              "      <div class=\"spacediv\"> </div>"
              "      <div>"
              "        <input type=\"password\" name=\"Passwort\" value=\"" + ConfigValue[9] + "\" />"
              "      </div>"
              "    </div>"
              "    <div class=\"container\">"
              "      <div>RESET</div>"
              "      <div class=\"spacediv\"> </div>"
              "      <div>"
              "        <input type=\"text\" class=\"reset\" name=\"RESET\" />"
              "      </div>"
              "    </div>"
              "    <div class=\"container\">"
              "      <div>"
//              "        <a href=\"http://" + WiFi.localIP().toString() + ":8080\" class=\"buttonstyle\">Firmware Update</a>"
              "        <a href=\"#\" onclick=\"window.open('http://" + WiFi.localIP().toString() + ":8080\'); window.open('http://" + WiFi.softAPIP().toString() + ":8080\');\" class=\"buttonstyle\">Firmware Update (ADMIN)</a>"
              "      </div>"
              "    </div>"
              "    <div class=\"spacer3\"></div>"
              "    <details>"
              "      <summary>Verfügbare Netzwerke</summary>"
              "      <div class=\"evencontainer\">"
              "        <div class=\"tablecontainer\">"
              "          <div>"
              "            <h3>Nr.</h3>"
              "          </div>"
              "        </div>"
              "        <div class=\"tablecontainer\">"
              "          <div>"
              "            <h3>Name</h3>"
              "          </div>"
              "        </div>"
              "        <div class=\"tablecontainer\">"
              "          <div>"
              "            <h3>Signal</h3>"
              "          </div>"
              "        </div>"
              "      </div>"
              "      <div class=\"evencontainer\">"
              "        <div class=\"tablecontainer\">";

  for (int i = 0; i < numberWlan; i++)
  {
    HTMLPage += "          <div>"
                "            <h5>" + String(i + 1) + "</h5>"
                "          </div>";
  }

  HTMLPage += "        </div>"
              "        <div class=\"tablecontainer\">";

  for (int i = 0; i < numberWlan; i++)
  {
    HTMLPage += "          <div>"
                "            <h5>" + Wlanssid[i] + "</h5>"
                "          </div>";
  }
  HTMLPage += "        </div>"
              "        <div class=\"tablecontainer\">";

  for (int i = 0; i < numberWlan; i++)
  {

    HTMLPage += "          <div>"
                "            <h5>" + Wlanrssi[i] + "%</h5>"
                "          </div>";
  }


  HTMLPage += "        </div>"
              "      </div>"
              "    </details>"
              "  </details>"
              "  </center>"
              "</form>"
              "<script>"
              "    var slider1 = document.getElementById(\"ledbrightness\");"
              "    var output1 = document.getElementById(\"demo\");"
              "    output1.innerHTML = slider1.value;"
              "    slider1.oninput = function() {"
              "        output1.innerHTML = this.value;"
              "    }"
              "</script> "
              "<script>"
              "    var slider2 = document.getElementById(\"ledbrightnessnight\");"
              "    var output2 = document.getElementById(\"lednight\");"
              "    output2.innerHTML = slider2.value;"
              "    slider2.oninput = function() {"
              "        output2.innerHTML = this.value;"
              "    }"
              "</script>"
              "</body>"
              "</html>";
  return HTMLPage;
}
