// ============= WEB APPLICATION SERVING =============
// Serves the Svelte frontend (compiled to webapp.h by svelteesp32)

// The webapp.h file is generated by running: cd frontend && npm run generate
// If it doesn't exist, a placeholder page will be shown instead

#ifdef __has_include
  #if __has_include("webapp.h")
    #define HAS_WEBAPP_H
    #include "webapp.h"
  #endif
#endif

void setupWebApp(AsyncWebServer &server) {
  // Captive portal detection - these URLs are checked by devices to detect login portals
  // iOS
  server.on("/hotspot-detect.html", HTTP_GET, [](AsyncWebServerRequest *request){
    request->redirect("http://192.168.4.1/");
  });
  // Android
  server.on("/generate_204", HTTP_GET, [](AsyncWebServerRequest *request){
    request->redirect("http://192.168.4.1/");
  });
  // Microsoft
  server.on("/connecttest.txt", HTTP_GET, [](AsyncWebServerRequest *request){
    request->redirect("http://192.168.4.1/");
  });
  // Firefox
  server.on("/success.txt", HTTP_GET, [](AsyncWebServerRequest *request){
    request->redirect("http://192.168.4.1/");
  });
  
  // Catch-all - redirect any other domain to our page
  server.onNotFound([](AsyncWebServerRequest *request){
    // Only redirect if it's not for our assets
    String host = request->host();
    if (host != "192.168.4.1" && !request->url().startsWith("/api") && !request->url().startsWith("/assets")) {
      request->redirect("http://192.168.4.1/");
    } else {
      request->send(404, "text/plain", "Not found");
    }
  });

#ifdef HAS_WEBAPP_H
  // Serve the compiled Svelte app from webapp.h
  initSvelteStaticFiles(&server);
  Serial.println("✅ Svelte web interface loaded");
#else
  // Temporary placeholder page until frontend is built
  server.on("/", HTTP_GET, [](AsyncWebServerRequest *request){
    String html = R"rawliteral(
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Wordclock Setup</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      display: flex;
      align-items: center;
      justify-content: center;
      min-height: 100vh;
      margin: 0;
      padding: 20px;
    }
    .card {
      background: rgba(255, 255, 255, 0.1);
      backdrop-filter: blur(10px);
      border-radius: 20px;
      padding: 40px;
      max-width: 600px;
      box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.37);
      border: 1px solid rgba(255, 255, 255, 0.18);
    }
    h1 { margin-top: 0; font-size: 2.5em; }
    .status { background: rgba(0, 255, 0, 0.2); padding: 15px; border-radius: 10px; margin: 20px 0; }
    .info { opacity: 0.9; line-height: 1.6; }
    .api-link {
      display: inline-block;
      background: rgba(255, 255, 255, 0.2);
      padding: 10px 20px;
      border-radius: 8px;
      margin: 10px 5px;
      text-decoration: none;
      color: white;
      transition: transform 0.2s;
    }
    .api-link:hover { transform: scale(1.05); }
    code {
      background: rgba(0, 0, 0, 0.3);
      padding: 2px 8px;
      border-radius: 4px;
      font-family: 'Courier New', monospace;
    }
  </style>
</head>
<body>
  <div class="card">
    <h1>🕐 Wordclock</h1>
    <div class="status">
      ✅ <strong>Firmware Running:</strong> Version )rawliteral" + String(FIRMWARE_VERSION) + R"rawliteral(
    </div>
    
    <div class="info">
      <h2>📦 Frontend Not Built Yet</h2>
      <p>The Svelte web interface needs to be compiled. Follow these steps:</p>
      
      <h3>Build Instructions:</h3>
      <ol>
        <li>Open terminal in the <code>frontend/</code> folder</li>
        <li>Run <code>npm install</code> (first time only)</li>
        <li>Run <code>npm run generate</code></li>
        <li>Upload firmware again (includes <code>webapp.h</code>)</li>
      </ol>
      
      <h3>📡 API Endpoints Available:</h3>
      <a href="/api/status" class="api-link">/api/status</a>
      <a href="/api/config" class="api-link">/api/config</a>
      
      <h3>💡 Current Status:</h3>
      <p>
        <strong>WiFi:</strong> )rawliteral" + String(WiFi.isConnected() ? "Connected" : "Disconnected") + R"rawliteral(<br>
        <strong>IP:</strong> )rawliteral" + WiFi.localIP().toString() + R"rawliteral(<br>
        <strong>Free Memory:</strong> )rawliteral" + String(ESP.getFreeHeap()) + R"rawliteral( bytes
      </p>
    </div>
  </div>
</body>
</html>
    )rawliteral";
    
    request->send(200, "text/html", html);
  });
  
  Serial.println("⚠️  Placeholder web interface active");
  Serial.println("💡 Build frontend with: cd frontend && npm run generate");
#endif
}
